[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["Pool"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
verbosity = 2

[dependencies]
#openzeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.2.0" }
#openzeppelin-upgradeable = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", tag = "v5.2.0" }
#forge-std = { git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.9.6" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[fmt]
line_length = 120
